dependencies:
 - hdf5=1.8.18
 - six
 - Cython
 - nose
 - numpy
 - numexpr
 - pyproj
 - PySide
 - pyqt=4
 - psutil
 - matplotlib<2
 - basemap
 - obspy
 - vispy
 - icu=56.*
 - libxslt=1.1.29=2
 - pip:
   - construct==2.5.1
   - simplekml
   - tables
   - flake8
