dependencies:
 - python=2.7
 - obspy=1.2.2
 - hdf5=1.8.18
 - pykml=0.1.0
 # workaround icu not from conda-forge
 - icu=58.*
 - Cython
 - nose
 - numexpr
 - pyproj
 - psutil
 - vispy
 - astropy
 - testfixtures  # development
 - pyside2
 - pip=20.1.1
 - pip:
   - construct==2.5.1
   - simplekml
   - tables==3.4.2
   - flake8      # development
   - coverage    # development
   - matplotlib==1.*
